fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.22.0'
    common:
      repo: 'https://github.com/ghoneycutt/puppet-module-common.git'
      ref: 'v1.4.1'
    nsswitch:
      repo: 'https://github.com/trlinkin/puppet-nsswitch.git'
      ref: '2.0.0'
  symlinks:
    pam: "#{source_dir}"
